apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ftps
  labels:
    app: ftps
  namespace: default
  labels:
    app: ftps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
      metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: port-ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: port-ftps-data
      protocol: TCP
      port: 50000
      targetPort: 50000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        #disable the ability to download an image from the docker hub
        imagePullPolicy: Never
        #open the port at the pod
        ports:
        - containerPort: 21
        - containerPort: 50000
