apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
      metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: mysql
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_image
        #disable the ability to download an image from the docker hub
        imagePullPolicy: Never
        #open the port at the pod
        ports:
        - containerPort: 3306
