apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
      metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - name: port-pma
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_image
        #disable the ability to download an image from the docker hub
        imagePullPolicy: Never
        #open the port at the pod
        ports:
        - containerPort: 5000
